name: List Terraform State

on:
  workflow_dispatch:
#  push:
 #   branches:
 #     - main
 # workflow_dispatch:  # allows manual triggering

jobs:
  list-terraform-state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0  # set your Terraform version

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform-cicd

      - name: List Terraform state
      #  run: terraform state list
        run: terraform state list -state=terraform-cicd/terraform.tfstate

